name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    working-directory: docs
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run generate
    - run: npm run deploy
      env:
        CI: true
